### ISSUE TITLE
add shortcut link to aavegotchi.com for the address 

### ISSUE THREAD

**Issue by yanik-ai** [orden-gg/fireball#117]
<img width="1128" alt="Screenshot 2021-11-15 at 12 48 18" src="https://user-images.githubusercontent.com/3940227/141769028-b297ffb5-d8af-4d64-9206-de25b5a7556c.png">

- [ ] button to copy with 1 click 
- [ ] display qr code for the address
- [ ] `https://www.aavegotchi.com/aavegotchis/ADDR` link for the address 

everything should be with dimmed buttons, similar to gnosis: 
![image](https://user-images.githubusercontent.com/3940227/141769304-effb3a12-bbb4-4551-892e-8cfbc001e7ec.png)

**Comment by dudendy** [comment]
already implemented
