### ISSUE TITLE
add address signatures UX-only

### ISSUE THREAD

**Issue by yanik-ai** [orden-gg/fireball#169]
add signatures support for users logged in with metamask 

similar to: 

https://codesandbox.io/s/react-eth-metamask-signatures-ibuxj?file=/src/App.js 

https://www.youtube.com/watch?v=vhUjCLYlnMM

**Comment by yanik-ai** [comment]
this feature is required for guild-based features and allychat

**Comment by dudendy** [comment]
moving to `archive`
