### ISSUE TITLE
use binomial distribution for raffle result estimation 

### ISSUE THREAD

**Issue by yanik-ai** [orden-gg/fireball#172]
https://homepage.divms.uiowa.edu/~mbognar/applets/bin.html

**Comment by yanik-ai** [comment]
amazing sheet https://docs.google.com/spreadsheets/d/1HIsYxvwtCH4-ok0zu9HYW8NTiXr3yEO3LJqfRhrL7I0/edit#gid=0

**Comment by yanik-ai** [comment]
another amazing tool https://gotchiaaltar.herokuapp.com/

**Comment by zerkben** [comment]
Created the pull request by deploying the source code of the above mentioned web app in ghst.gg repo

**Comment by dudendy** [comment]
moving to `archive`
