### ISSUE TITLE
FRENs transparency page

### ISSUE THREAD

**Issue by yanik-ai** [orden-gg/fireball#174]
currently, the FREN's inflation is a major mean of GHST value, but also a main inflation point for people who hold in-game assets like aavegotchis (characters) or other game items. Since thous'e NFTS are inflated and distributed to FRENs holders, apart of being sold for Aavegotchi DAO development and haunt reward fund. 

**therefore It is crucial to provide the public data on who is receiving FREN's and for what contribution.**

**Comment by dudendy** [comment]
moving to `archive`
