### ISSUE TITLE
ghost character type

### ISSUE THREAD

**Issue by yanik-ai** [orden-gg/fireball#179]
Change the gotchi card so it visually represents the character type
One option would be to go with radar chart 

![image](https://user-images.githubusercontent.com/3940227/152329311-3c8a879d-c8c9-409c-ab64-ebbce4e2dd4a.png)
![image](https://user-images.githubusercontent.com/3940227/152329559-b1cf335e-985a-49c2-88a0-8bf4e47da01a.png)

**Comment by yanik-ai** [comment]
I see the two potential options: 

(1) add it as a to a hover block 
(2) remove base stats, but add trait icon (leave modified stat)

**Comment by dudendy** [comment]
already implemented ✅
