### ISSUE TITLE
display badges in gothi client 

### ISSUE THREAD

**Issue by yanik-ai** [orden-gg/fireball#328]
Badges are fundamental to understand how valuable the gotchi is. 
We need to show it in client. 

- display badges from pocket
- icons are the same size as gotchi channeling status and are based next to channeling status  
- display only 1 row max, if gotchi has more add  [+X] button which will flip the card and display all badges (badges only,  for now) 
  

<img width="196" alt="image" src="https://user-images.githubusercontent.com/3940227/176131961-060b5db5-881d-4849-848e-b8bf73c2f1c3.png">

ttps://app.aavegotchi.com/gotchi/5010/pocket
<img width="381" alt="image" src="https://user-images.githubusercontent.com/3940227/176132449-f2c6ff11-b5be-4a36-8822-9a167e0f3845.png">

**Comment by dudendy** [comment]
already implemented ✅
