### ISSUE TITLE
Game Events 

### ISSUE THREAD

**Issue by yanik-ai** [orden-gg/fireball#36]
Page display live events from aavegotchi metaverse: 

- [ ] portal open
- [ ] gotchi summoned 
- [ ] item soled 

to consider: 
- [ ] raffle events (tickets added) 
- [ ] but / sell from quickswap GHST 
- [ ] associate each address with strongest aavegotchi for now, and let users to choose "account aavegotchi" later on

**Comment by dudendy** [comment]
moving to `archive`
