### ISSUE TITLE
aavegotchi apple watch card

### ISSUE THREAD

**Issue by yanik-ai** [orden-gg/fireball#372]
create download-only aavegotchi for apple watch.

must contain base info and look cool on watch! 

stats to show: 
- got6chi name + id
- kin

not ideal example 
![IMAGE 2022-07-17 17:41:05](https://user-images.githubusercontent.com/3940227/179394536-5a242f73-9951-45b1-8d47-6e8abd7d7e63.jpg)

<img width="161" alt="image" src="https://user-images.githubusercontent.com/3940227/179751505-4def8471-d112-443f-871a-4c1f33e3b9bd.png">

**Comment by dudendy** [comment]
moving to `archive`
