### ISSUE TITLE
display parcel survey achemica 

### ISSUE THREAD

**Issue by yanik-ai** [orden-gg/fireball#377]
<img width="968" alt="image" src="https://user-images.githubusercontent.com/3940227/180015127-3dc10ad2-3161-4118-bb82-b5726fb60a8d.png">

**Comment by dudendy** [comment]
I would also suggest visually display the current round alchemica survey roll (below or above avarage)
all methods for this are available in `realm` diamond.

Also would be nice to have Act 1 / Round 1-10 separated info (only for parcel modal or single page)

more info here https://blog.aavegotchi.com/the-gotchiverse-game-bible-chapter-2/#average-alchemica-per-parcel-confirmed-in-paatch-v01
