### ISSUE TITLE
add items page

### ISSUE THREAD

**Issue by yanik-ai** [orden-gg/fireball#393]
<img width="45" alt="image" src="https://user-images.githubusercontent.com/3940227/182503366-0461d921-08fe-48e5-93bf-671607d24a98.png">

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/3940227/182503417-2188e118-87e1-43d7-a1c1-132861c8955c.png">

- similar to warehouse but with all items in aavegotchi game 
- card should include proposed effect , type, total qty , etc

**Comment by dudendy** [comment]
i would suggest to make `Glossary` page with all available items, installations, tiles and others on gotchiverse
