### ISSUE TITLE
update for gotchi explorer

### ISSUE THREAD

**Issue by yanik-ai** [orden-gg/fireball#394]
<img width="154" alt="image" src="https://user-images.githubusercontent.com/3940227/182516138-82464f09-0ab5-4ed7-9318-f7be2e719b70.png">

- [ ]  replace gotchi race with number (example: `#55 `) which is representing the position of current gotchi in filter/sorting result 
- [ ] add filter by rare eyes: (A) double myth eyes (B) myth/rare combination (C) double rare eyes

**Comment by dudendy** [comment]
moving to `archive`
